scorpio.messageconnection.bootstrap.host=${bushost:localhost}
scorpio.messageconnection.bootstrap.port=${busport:1883}
bootstrap.servers=${scorpio.messageconnection.bootstrap.host}:${scorpio.messageconnection.bootstrap.port}
scorpio.messageconnection.protocol=paho-mqtt5
scorpio.messageconnection.options=
camel.component.paho-mqtt5.broker-url=tcp://${bootstrap.servers}
scorpio.messaging.maxSize=1048576
mp.messaging.incoming.registryretrieve.connector=smallrye-camel
mp.messaging.incoming.registryretrieve.endpoint-uri=${scorpio.messageconnection.protocol}:${scorpio.topics.registry}${scorpio.messageconnection.options}
mp.messaging.incoming.registryretrieve.auto.offset.reset=latest
mp.messaging.incoming.registryretrieve.broadcast=true
scorpio.startupdelay=10s
