---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: 555496e2de3765466a67664fc5046ce0499b0505
    app.quarkus.io/vcs-uri: https://github.com/scorpiobroker/scorpiobroker.git
    app.quarkus.io/build-timestamp: 2026-01-12 - 13:31:23 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "10096"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: history-query-manager
    app.kubernetes.io/version: 6.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: history-query-manager
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: history-query-manager
    app.kubernetes.io/version: 6.0.1-SNAPSHOT
  type: ClusterIP
