package eu.neclab.ngsildbroker.commons.enums;

import java.util.Set;

import eu.neclab.ngsildbroker.commons.constants.NGSIConstants;

/**
 * One constant per NGSI-LD endpoint operation. Each carries the exact set of
 * query parameters the operation accepts; anything else is rejected with 400
 * InvalidRequest (spec clause 6.3.20) by
 * {@link eu.neclab.ngsildbroker.commons.tools.QueryParamParser}.
 */
public enum NgsiLdOperation {

	RETRIEVE_ENTITY(P.RETRIEVE_ENTITY),
	QUERY_ENTITIES(P.QUERY_ENTITIES),
	PURGE_ENTITIES(P.PURGE_ENTITIES),
	CREATE_ENTITY_MAP(P.CREATE_ENTITY_MAP),
	RETRIEVE_TYPES(P.RETRIEVE_TYPES),
	RETRIEVE_TYPE(P.LOCAL_ONLY),
	RETRIEVE_ATTRIBUTES(P.DETAILS_LOCAL),
	RETRIEVE_ATTRIBUTE(P.DETAILS_LOCAL),
	APPEND_ENTITY_ATTRS(P.OPTIONS_LOCAL),
	DELETE_ATTR(P.DELETE_ATTR),
	BATCH_CREATE(P.LOCAL_ONLY),
	BATCH_UPSERT(P.OPTIONS_LOCAL),
	BATCH_UPDATE(P.OPTIONS_LOCAL),
	BATCH_MERGE(P.OPTIONS_LOCAL),
	BATCH_DELETE(P.LOCAL_ONLY),
	BATCH_QUERY(P.BATCH_QUERY),
	// spec 6.3.18: ALL operations on /entities, /entityOperations and
	// /temporal/entities (incl. child resources) must accept the "local"
	// parameter; Scorpio ignores it where it has no distributed variant
	CREATE_ENTITY(P.LOCAL_ONLY),
	UPDATE_ENTITY_ATTRS(P.LOCAL_ONLY),
	PARTIAL_UPDATE_ATTR(P.LOCAL_ONLY),
	DELETE_ENTITY(P.LOCAL_ONLY),
	MERGE_PATCH(P.LOCAL_ONLY),
	REPLACE_ENTITY(P.LOCAL_ONLY),
	REPLACE_ATTR(P.LOCAL_ONLY),
	RETRIEVE_ENTITY_MAP(P.NONE),
	UPDATE_ENTITY_MAP(P.NONE),
	DELETE_ENTITY_MAP(P.NONE),
	CREATE_SUBSCRIPTION(P.NONE),
	QUERY_SUBSCRIPTIONS(P.QUERY_SUBSCRIPTIONS),
	RETRIEVE_SUBSCRIPTION(P.OPTIONS_ONLY),
	UPDATE_SUBSCRIPTION(P.NONE),
	DELETE_SUBSCRIPTION(P.NONE),
	CREATE_CSOURCE(P.NONE),
	QUERY_CSOURCES(P.QUERY_CSOURCES),
	RETRIEVE_CSOURCE(P.NONE),
	UPDATE_CSOURCE(P.NONE),
	DELETE_CSOURCE(P.NONE),
	CREATE_TEMPORAL(P.LOCAL_ONLY),
	QUERY_TEMPORAL(P.QUERY_TEMPORAL),
	RETRIEVE_TEMPORAL(P.RETRIEVE_TEMPORAL),
	DELETE_TEMPORAL(P.LOCAL_ONLY),
	APPEND_TEMPORAL_ATTRS(P.LOCAL_ONLY),
	DELETE_TEMPORAL_ATTR(P.DELETE_ATTR),
	UPDATE_TEMPORAL_ATTR_INSTANCE(P.LOCAL_ONLY),
	DELETE_TEMPORAL_ATTR_INSTANCE(P.LOCAL_ONLY),
	TEMPORAL_BATCH_QUERY(P.TEMPORAL_BATCH_QUERY),
	RETRIEVE_CONTEXT(P.RETRIEVE_CONTEXT),
	QUERY_CONTEXTS(P.QUERY_CONTEXTS),
	CREATE_CONTEXT(P.NONE),
	DELETE_CONTEXT(P.DELETE_CONTEXT),
	CACHE_CONTEXT(P.NONE),
	CREATE_CONTEXT_IMPLICIT(P.NONE),
	INFO(P.NONE);

	private final Set<String> allowedParams;

	NgsiLdOperation(Set<String> allowedParams) {
		this.allowedParams = allowedParams;
	}

	public Set<String> getAllowedParams() {
		return allowedParams;
	}

	// enum constructors cannot reference enum statics, so the shared sets live
	// in this nested holder
	private static final class P {

		private P() {
		}

		static final Set<String> NONE = Set.of();

		static final Set<String> LOCAL_ONLY = Set.of(NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY);

		static final Set<String> OPTIONS_ONLY = Set.of(NGSIConstants.QUERY_PARAMETER_OPTIONS);

		static final Set<String> OPTIONS_LOCAL = Set.of(NGSIConstants.QUERY_PARAMETER_OPTIONS,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY, NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY);

		static final Set<String> DETAILS_LOCAL = Set.of(NGSIConstants.QUERY_PARAMETER_DETAILS,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY, NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY);

		static final Set<String> DELETE_ATTR = Set.of(NGSIConstants.QUERY_PARAMETER_DATA_SET_ID,
				NGSIConstants.QUERY_PARAMETER_DELETE_ALL, NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY);

		static final Set<String> RETRIEVE_ENTITY = Set.of(NGSIConstants.QUERY_PARAMETER_ATTRS,
				NGSIConstants.QUERY_PARAMETER_OPTIONS, NGSIConstants.QUERY_PARAMETER_LANG,
				NGSIConstants.QUERY_PARAMETER_GEOMETRY_PROPERTY, NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY, NGSIConstants.QUERY_PARAMETER_DO_NOT_COMPACT,
				NGSIConstants.QUERY_PARAMETER_CONTAINED_BY, NGSIConstants.QUERY_PARAMETER_JOIN,
				NGSIConstants.QUERY_PARAMETER_JOINLEVEL, NGSIConstants.QUERY_PARAMETER_PICK,
				NGSIConstants.QUERY_PARAMETER_OMIT, NGSIConstants.QUERY_PARAMETER_FORMAT,
				NGSIConstants.QUERY_PARAMETER_ENTITY_MAP, NGSIConstants.QUERY_PARAMETER_DATA_SET_ID,
				NGSIConstants.QUERY_PARAMETER_SPLIT_ENTITIES, NGSIConstants.QUERY_PARAMETER_TYPE);

		static final Set<String> QUERY_ENTITIES = Set.of(NGSIConstants.QUERY_PARAMETER_ID,
				NGSIConstants.QUERY_PARAMETER_TYPE, NGSIConstants.QUERY_PARAMETER_IDPATTERN,
				NGSIConstants.QUERY_PARAMETER_ATTRS, NGSIConstants.QUERY_PARAMETER_QUERY,
				NGSIConstants.QUERY_PARAMETER_CSF, NGSIConstants.QUERY_PARAMETER_GEOMETRY,
				NGSIConstants.QUERY_PARAMETER_GEOREL, NGSIConstants.QUERY_PARAMETER_COORDINATES,
				NGSIConstants.QUERY_PARAMETER_GEOPROPERTY, NGSIConstants.QUERY_PARAMETER_GEOMETRY_PROPERTY,
				NGSIConstants.QUERY_PARAMETER_LANG, NGSIConstants.QUERY_PARAMETER_SCOPE_QUERY,
				NGSIConstants.QUERY_PARAMETER_MAX_DISTANCE, NGSIConstants.QUERY_PARAMETER_MIN_DISTANCE,
				NGSIConstants.QUERY_PARAMETER_PICK, NGSIConstants.QUERY_PARAMETER_OMIT,
				NGSIConstants.QUERY_PARAMETER_JSON_KEYS, NGSIConstants.QUERY_PARAMETER_DATA_SET_ID,
				NGSIConstants.QUERY_PARAMETER_SPLIT_ENTITIES, NGSIConstants.QUERY_PARAMETER_ORDER_BY,
				NGSIConstants.QUERY_PARAMETER_ORDER_FROM, NGSIConstants.QUERY_PARAMETER_ORDER_GEOMETRY,
				NGSIConstants.QUERY_PARAMETER_ORDER_COLLATION, NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY, NGSIConstants.QUERY_PARAMETER_OPTIONS,
				NGSIConstants.QUERY_PARAMETER_LIMIT, NGSIConstants.QUERY_PARAMETER_OFFSET,
				NGSIConstants.QUERY_PARAMETER_COUNT, NGSIConstants.QUERY_PARAMETER_CONTAINED_BY,
				NGSIConstants.QUERY_PARAMETER_JOIN, NGSIConstants.QUERY_PARAMETER_JOINLEVEL,
				NGSIConstants.QUERY_PARAMETER_DO_NOT_COMPACT, NGSIConstants.QUERY_PARAMETER_ENTITY_MAP,
				NGSIConstants.QUERY_PARAMETER_FORMAT, NGSIConstants.QUERY_PARAMETER_META_DATA);

		static final Set<String> PURGE_ENTITIES = Set.of(NGSIConstants.QUERY_PARAMETER_ID,
				NGSIConstants.QUERY_PARAMETER_TYPE, NGSIConstants.QUERY_PARAMETER_IDPATTERN,
				NGSIConstants.QUERY_PARAMETER_ATTRS, NGSIConstants.QUERY_PARAMETER_QUERY,
				NGSIConstants.QUERY_PARAMETER_CSF, NGSIConstants.QUERY_PARAMETER_GEOMETRY,
				NGSIConstants.QUERY_PARAMETER_GEOREL, NGSIConstants.QUERY_PARAMETER_COORDINATES,
				NGSIConstants.QUERY_PARAMETER_GEOPROPERTY, NGSIConstants.QUERY_PARAMETER_SCOPE_QUERY,
				NGSIConstants.QUERY_PARAMETER_MAX_DISTANCE, NGSIConstants.QUERY_PARAMETER_MIN_DISTANCE,
				NGSIConstants.QUERY_PARAMETER_DROP, NGSIConstants.QUERY_PARAMETER_KEEP,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY, NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY);

		static final Set<String> CREATE_ENTITY_MAP = Set.of(NGSIConstants.QUERY_PARAMETER_ID,
				NGSIConstants.QUERY_PARAMETER_TYPE, NGSIConstants.QUERY_PARAMETER_IDPATTERN,
				NGSIConstants.QUERY_PARAMETER_ATTRS, NGSIConstants.QUERY_PARAMETER_QUERY,
				NGSIConstants.QUERY_PARAMETER_CSF, NGSIConstants.QUERY_PARAMETER_GEOMETRY,
				NGSIConstants.QUERY_PARAMETER_GEOREL, NGSIConstants.QUERY_PARAMETER_COORDINATES,
				NGSIConstants.QUERY_PARAMETER_GEOPROPERTY, NGSIConstants.QUERY_PARAMETER_GEOMETRY_PROPERTY,
				NGSIConstants.QUERY_PARAMETER_LANG, NGSIConstants.QUERY_PARAMETER_SCOPE_QUERY,
				NGSIConstants.QUERY_PARAMETER_MAX_DISTANCE, NGSIConstants.QUERY_PARAMETER_MIN_DISTANCE,
				NGSIConstants.QUERY_PARAMETER_PICK, NGSIConstants.QUERY_PARAMETER_OMIT,
				NGSIConstants.QUERY_PARAMETER_JSON_KEYS, NGSIConstants.QUERY_PARAMETER_DATA_SET_ID,
				NGSIConstants.QUERY_PARAMETER_SPLIT_ENTITIES, NGSIConstants.QUERY_PARAMETER_ORDER_BY,
				NGSIConstants.QUERY_PARAMETER_ORDER_FROM, NGSIConstants.QUERY_PARAMETER_ORDER_GEOMETRY,
				NGSIConstants.QUERY_PARAMETER_ORDER_COLLATION);

		static final Set<String> RETRIEVE_TYPES = Set.of(NGSIConstants.QUERY_PARAMETER_DETAILS,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY, NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY,
				NGSIConstants.QUERY_PARAMETER_BBOX);

		static final Set<String> BATCH_QUERY = Set.of(NGSIConstants.QUERY_PARAMETER_LIMIT,
				NGSIConstants.QUERY_PARAMETER_OFFSET, NGSIConstants.QUERY_PARAMETER_OPTIONS,
				NGSIConstants.QUERY_PARAMETER_COUNT, NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY, NGSIConstants.QUERY_PARAMETER_GEOMETRY_PROPERTY,
				NGSIConstants.QUERY_PARAMETER_ENTITY_MAP, NGSIConstants.QUERY_PARAMETER_DO_NOT_COMPACT);

		static final Set<String> QUERY_SUBSCRIPTIONS = Set.of(NGSIConstants.QUERY_PARAMETER_LIMIT,
				NGSIConstants.QUERY_PARAMETER_OFFSET, NGSIConstants.QUERY_PARAMETER_OPTIONS,
				NGSIConstants.QUERY_PARAMETER_COUNT);

		static final Set<String> QUERY_CSOURCES = Set.of(NGSIConstants.QUERY_PARAMETER_ID,
				NGSIConstants.QUERY_PARAMETER_TYPE, NGSIConstants.QUERY_PARAMETER_IDPATTERN,
				NGSIConstants.QUERY_PARAMETER_ATTRS, NGSIConstants.QUERY_PARAMETER_QUERY,
				NGSIConstants.QUERY_PARAMETER_CSF, NGSIConstants.QUERY_PARAMETER_GEOMETRY,
				NGSIConstants.QUERY_PARAMETER_GEOREL, NGSIConstants.QUERY_PARAMETER_COORDINATES,
				NGSIConstants.QUERY_PARAMETER_GEOPROPERTY, NGSIConstants.QUERY_PARAMETER_GEOMETRY_PROPERTY,
				NGSIConstants.QUERY_PARAMETER_TIMEPROPERTY, NGSIConstants.QUERY_PARAMETER_TIMEREL,
				NGSIConstants.QUERY_PARAMETER_SCOPE_QUERY, NGSIConstants.QUERY_PARAMETER_TIME,
				NGSIConstants.QUERY_PARAMETER_ENDTIME, NGSIConstants.QUERY_PARAMETER_MAX_DISTANCE,
				NGSIConstants.QUERY_PARAMETER_MIN_DISTANCE, NGSIConstants.QUERY_PARAMETER_LIMIT,
				NGSIConstants.QUERY_PARAMETER_OFFSET, NGSIConstants.QUERY_PARAMETER_OPTIONS,
				NGSIConstants.QUERY_PARAMETER_COUNT);

		static final Set<String> QUERY_TEMPORAL = Set.of(NGSIConstants.QUERY_PARAMETER_ID,
				NGSIConstants.QUERY_PARAMETER_TYPE, NGSIConstants.QUERY_PARAMETER_IDPATTERN,
				NGSIConstants.QUERY_PARAMETER_ATTRS, NGSIConstants.QUERY_PARAMETER_QUERY,
				NGSIConstants.QUERY_PARAMETER_CSF, NGSIConstants.QUERY_PARAMETER_GEOMETRY,
				NGSIConstants.QUERY_PARAMETER_GEOREL, NGSIConstants.QUERY_PARAMETER_COORDINATES,
				NGSIConstants.QUERY_PARAMETER_GEOPROPERTY, NGSIConstants.QUERY_PARAMETER_MAX_DISTANCE,
				NGSIConstants.QUERY_PARAMETER_MIN_DISTANCE, NGSIConstants.QUERY_PARAMETER_TIMEPROPERTY,
				NGSIConstants.QUERY_PARAMETER_TIMEREL, NGSIConstants.QUERY_PARAMETER_TIME,
				NGSIConstants.QUERY_PARAMETER_ENDTIME, NGSIConstants.QUERY_PARAMETER_SCOPE_QUERY,
				NGSIConstants.QUERY_PARAMETER_LANG, NGSIConstants.QUERY_PARAMETER_AGGR_METHODS,
				NGSIConstants.QUERY_PARAMETER_AGGR_PERIOD_DURATION, NGSIConstants.QUERY_PARAMETER_ENTITY_MAP,
				NGSIConstants.QUERY_PARAMETER_OPTIONS, NGSIConstants.QUERY_PARAMETER_COUNT,
				NGSIConstants.QUERY_PARAMETER_FORMAT, NGSIConstants.QUERY_PARAMETER_LAST_N,
				NGSIConstants.QUERY_PARAMETER_N, NGSIConstants.QUERY_PARAMETER_FIRST_N,
				NGSIConstants.QUERY_PARAMETER_OFFSET_N, NGSIConstants.QUERY_PARAMETER_ORDER_N,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY, NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY,
				NGSIConstants.QUERY_PARAMETER_LIMIT, NGSIConstants.QUERY_PARAMETER_OFFSET);

		static final Set<String> RETRIEVE_TEMPORAL = Set.of(NGSIConstants.QUERY_PARAMETER_ATTRS,
				NGSIConstants.QUERY_PARAMETER_AGGR_METHODS, NGSIConstants.QUERY_PARAMETER_AGGR_PERIOD_DURATION,
				NGSIConstants.QUERY_PARAMETER_LANG, NGSIConstants.QUERY_PARAMETER_LAST_N,
				NGSIConstants.QUERY_PARAMETER_OPTIONS, NGSIConstants.QUERY_PARAMETER_GEOMETRY_PROPERTY,
				NGSIConstants.QUERY_PARAMETER_TIMEPROPERTY, NGSIConstants.QUERY_PARAMETER_TIMEREL,
				NGSIConstants.QUERY_PARAMETER_TIME, NGSIConstants.QUERY_PARAMETER_ENDTIME,
				NGSIConstants.QUERY_PARAMETER_FORMAT, NGSIConstants.QUERY_PARAMETER_N,
				NGSIConstants.QUERY_PARAMETER_OFFSET_N, NGSIConstants.QUERY_PARAMETER_ORDER_N,
				NGSIConstants.QUERY_PARAMETER_FIRST_N, NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY);

		static final Set<String> TEMPORAL_BATCH_QUERY = Set.of(NGSIConstants.QUERY_PARAMETER_LIMIT,
				NGSIConstants.QUERY_PARAMETER_OFFSET, NGSIConstants.QUERY_PARAMETER_LAST_N,
				NGSIConstants.QUERY_PARAMETER_OPTIONS, NGSIConstants.QUERY_PARAMETER_COUNT,
				NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY, NGSIConstants.QUERY_PARAMETER_LOCAL_ONLY_LEGACY,
				NGSIConstants.QUERY_PARAMETER_GEOMETRY_PROPERTY, NGSIConstants.QUERY_PARAMETER_ENTITY_MAP,
				NGSIConstants.QUERY_PARAMETER_DO_NOT_COMPACT, NGSIConstants.QUERY_PARAMETER_N,
				NGSIConstants.QUERY_PARAMETER_OFFSET_N, NGSIConstants.QUERY_PARAMETER_N_ORDER);

		// "type" is not spec'd here but Scorpio itself appends
		// ?type=implicitlyCreated to hosted context URLs (SubscriptionController),
		// so dereferencing those URLs must keep working
		static final Set<String> RETRIEVE_CONTEXT = Set.of(NGSIConstants.QUERY_PARAMETER_DETAILS,
				NGSIConstants.QUERY_PARAMETER_TYPE);

		static final Set<String> QUERY_CONTEXTS = Set.of(NGSIConstants.QUERY_PARAMETER_KIND,
				NGSIConstants.QUERY_PARAMETER_DETAILS);

		static final Set<String> DELETE_CONTEXT = Set.of(NGSIConstants.QUERY_PARAMETER_RELOAD);
	}
}
