mysettings:
  application-name: query-manager
  kafka:
    bootstrap:
      host: ${kafka.host:kafka}
      port: ${kafka.port:9092}
  postgres:
    host: ${dbhost:postgres}
    port: ${dbport:5432}
    username: ${dbuser:ngb}
    password: ${dbpass:ngb}
    database-name: ${dbname:ngb}
  gateway:
    host: ${gateway.host:}
    port: ${gateway.port:9090}