FROM eclipse-temurin:21-jre-ubi9-minimal
WORKDIR /usr/src/scorpio
COPY target/quarkus-app ./
ENV DBHOST=postgres
ENV BUSHOST=kafka
EXPOSE 9090
CMD java --enable-native-access=ALL-UNNAMED -jar quarkus-run.jar
