apiVersion: v1
kind: Service
metadata:
  labels:
      component: scorpio
  name: scorpio
  namespace: scorpio-broker
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
      component: scorpio
status:
  loadBalancer: {}
