apiVersion: v1
kind: Service
metadata:
  labels:
      component: scorpio
  name: scorpio-node-port
  namespace: scorpio-broker
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort : 30000
  selector:
      component: scorpio

