apiVersion: v1
kind: Service
metadata:
  labels:
    service: atcontext-server
  name: atcontext-server
  namespace: scorpio-broker
spec:
  type: NodePort
  ports:
  - port: 27015
    targetPort: 27015
    nodePort: 30010
  selector:
    service: atcontext-server
status: {}
