apiVersion: v1
kind: Service
metadata:
  labels:
    service: entity-manager
  name: entity-manager
  namespace: scorpio-broker
spec:
  type: NodePort
  ports:
  - port: 1025
    targetPort: 1025
    nodePort: 30011
  selector:
    service: entity-manager
status: {}

