apiVersion: v1
kind: Service
metadata:
  labels:
    service: history-manager
  name: history-manager
  namespace: scorpio-broker
spec:
  type: NodePort
  ports:
  - port: 1040
    targetPort: 1040
    nodePort: 30012
  selector:
    service: history-manager
status: {}

