apiVersion: v1
kind: Service
metadata:
  labels:
    service: registry-subscription-manager
  name: registry-subscription-manager
  namespace: scorpio-broker
spec:
  type: NodePort
  ports:
  - port: 2025
    targetPort: 2025
    nodePort: 30015
  selector:
    service: registry-subscription-manager
status: {}

