apiVersion: v1
kind: Service
metadata:
  labels:
    service: registry-manager
  name: registry-manager
  namespace: scorpio-broker
spec:
  type: NodePort
  ports:
  - port: 1030
    targetPort: 1030
    nodePort: 30014
  selector:
    service: registry-manager
status: {}

