apiVersion: v1
kind: Service
metadata:
  labels:
    service: registry-manager
  name: registry-manager
  namespace: scorpio-broker
spec:
  ports:
  - name: "1030"
    port: 1030
    targetPort: 1030
  selector:
    service: registry-manager
status: {}

