apiVersion: v1
kind: Service
metadata:
  labels:
    service: subscription-manager
  name: subscription-manager
  namespace: scorpio-broker
spec:
  ports:
  - name: "2026"
    port: 2026
    targetPort: 2026
  selector:
    service: subscription-manager
status: {}

