apiVersion: v1
kind: Service
metadata:
  labels:
    service: subscription-manager
  name: subscription-manager
  namespace: scorpio-broker
spec:
  type: NodePort
  ports:
  - port: 2027
    targetPort: 2027
    nodePort: 30016
  selector:
    service: subscription-manager
status: {}

