version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181"
    logging:
      driver: none
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_RETENTION_MS: 30000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none

  postgres:
    image: mdillon/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    logging:
      driver: none
  scorpio:
    image: scorpiobroker/scorpio:scorpio-aaio_0.9.2-SNAPSHOT
    ports:
      - "9090:9090"
    depends_on:
      - kafka
      - postgres    
