scorpio.messageconnection.bootstrap.host=${bushost:localhost}
scorpio.messageconnection.bootstrap.port=${busport:5672}
bootstrap.servers=${scorpio.messageconnection.bootstrap.host}:${scorpio.messageconnection.bootstrap.port}
scorpio.messageconnection.protocol=rabbitmq
scorpio.messageconnection.options=
#?addresses=localhost:5672
scorpio.messaging.maxSize=134217728
mp.messaging.outgoing.registry.endpoint-uri=${scorpio.messageconnection.protocol}:${scorpio.topics.registry}${scorpio.messageconnection.options}
mp.messaging.outgoing.registry.connector=smallrye-camel
camel.component.rabbitmq.hostname=localhost
camel.component.rabbitmq.port-number=5672
