scorpio.messageconnection.bootstrap.host=${bushost:localhost}
scorpio.messageconnection.bootstrap.port=${busport:9092}
bootstrap.servers=${scorpio.messageconnection.bootstrap.host}:${scorpio.messageconnection.bootstrap.port}
client-id-prefix=$[quarkus.uuid}
group.id=$[quarkus.application.name}$[quarkus.uuid}
scorpio.messaging.maxSize=1048576
#Kafka settings
kafka.bootstrap.servers=${bootstrap.servers}
mp.messaging.outgoing.registry.topic=${scorpio.topics.registry}
mp.messaging.outgoing.registry.connector=smallrye-kafka
