---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: 59675831de0ce7a6ee91ff20efd25a8e6581e7a9
    app.quarkus.io/vcs-uri: https://github.com/scorpiobroker/scorpiobroker.git
    app.quarkus.io/build-timestamp: 2026-06-24 - 13:49:58 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "10091"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: query-manager
    app.kubernetes.io/version: 6.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: query-manager
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: query-manager
    app.kubernetes.io/version: 6.0.1-SNAPSHOT
  type: ClusterIP
