---
# Source: scorpioBroker/templates/config-server-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: config-server
  name: config-server
  namespace: scorpio-broker
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    service: config-server
status: {}
