---
# Source: scorpioBroker/templates/config-server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: config-server
  name: config-server
  namespace: scorpio-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: config-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: config-server
    spec:
      containers:
      - image: scorpiobroker/scorpio:config-server_latest
        imagePullPolicy: Always
        name: config-server
        ports:
        - containerPort: 8888
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/CONFIGSERVER/$HOSTNAME:configserver:8888/status?value=OUT_OF_SERVICE"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:8888/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: 6
          initialDelaySeconds: 40
          periodSeconds: 10
        resources:
          {}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
