---
# Source: scorpioBroker/templates/eureka-server-hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: eureka-hpa
 namespace: scorpio-broker
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: eureka
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 80
