---
# Source: scorpioBroker/templates/eureka-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: eureka
  name: eureka
  namespace: scorpio-broker
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    service: eureka
status: {}
