---
# Source: scorpioBroker/templates/gateway-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: gateway
  name: gateway
  namespace: scorpio-broker
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: gateway
status: {}
