---
# Source: scorpioBroker/templates/gateway-server-hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: gateway-hpa
 namespace: scorpio-broker
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: gateway
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 80
