---
# Source: scorpioBroker/templates/query-manager-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: query-manager
  name: query-manager
  namespace: scorpio-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: query-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: query-manager
    spec:
      containers:
      - image: scorpiobroker/scorpio:QueryManager_latest
        imagePullPolicy: Always
        name: query-manager
        ports:
        - containerPort: 1026
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/QUERY-MANAGER/$HOSTNAME:query-manager:1026/status?value=OUT_OF_SERVICE"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:1026/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: 6
          initialDelaySeconds: 40
          periodSeconds: 10
        resources:
          {}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
