---
# Source: scorpioBroker/templates/storage-manager-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: storage-manager
  name: storage-manager
  namespace: scorpio-broker
spec:
  ports:
  - name: "1029"
    port: 1029
    targetPort: 1029
  selector:
    service: storage-manager
status: {}
