---
# Source: scorpioBroker/templates/storage-manager-hpa.yml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: storage-manager-hpa
 namespace: scorpio-broker
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: storage-manager
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 80
