---
apiVersion: batch/v1
kind: Job
metadata:
  name: entity-manager-flyway-init
spec:
  completionMode: NonIndexed
  template:
    metadata: {}
    spec:
      containers:
        - env:
            - name: QUARKUS_FLYWAY_ACTIVE
              value: "true"
            - name: QUARKUS_INIT_AND_EXIT
              value: "true"
          image: docker.io/hebgen/entity-manager:6.0.1-SNAPSHOT
          name: entity-manager-flyway-init
      restartPolicy: OnFailure
      serviceAccountName: entity-manager
