---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: 5b071181a29f961b54fc0809638df14e0a08191a
    app.quarkus.io/vcs-uri: https://github.com/scorpiobroker/scorpiobroker.git
    app.quarkus.io/build-timestamp: 2026-01-08 - 14:59:25 +0000
  labels:
    app.kubernetes.io/name: entity-manager
    app.kubernetes.io/version: 6.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: entity-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: entity-manager
      app.kubernetes.io/version: 6.0.0-SNAPSHOT
  endpoints:
    - scheme: http
      targetPort: 10090
      path: /q/metrics
      interval: 10s
      honorLabels: true
