apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: atcontext-server
  name: atcontext-server
  namespace: scorpio-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: atcontext-server
  strategy: {}
  template:
    metadata:
      labels:
        service: atcontext-server
    spec:
      containers:
      - image: scorpiobroker/scorpio:AtContextServer_latest
        imagePullPolicy: Always
        name: atcontext-server
        ports:
        - containerPort: 27015
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/ATCONTEXT-SERVER/$HOSTNAME:atcontext-server:27015/status?value=OUT_OF_SERVICE"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:27015/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          limits:
            cpu: 575m
            memory: 2280Mi
          requests:
            cpu: 450m
            memory: 1850Mi
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

