apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: atcontext-server
  name: atcontext-server
  namespace: scorpio-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: atcontext-server
  strategy: {}
  template:
    metadata:
      labels:
        service: atcontext-server
    spec:
      containers:
      - image: scorpiobroker/at-context-server:spring-kafka-eureka-latest
        imagePullPolicy: Always
        name: atcontext-server
        ports:
        - containerPort: 27015
  
        resources:
          limits:
            cpu: 575m
            memory: 2280Mi
          requests:
            cpu: 450m
            memory: 1850Mi
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}


