apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: query-manager
  name: query-manager
  namespace: scorpio-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: query-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: query-manager
    spec:
      containers:
      - image: scorpiobroker/query-manager:spring-kafka-eureka-latest
        imagePullPolicy: Always
        name: query-manager
        ports:
        - containerPort: 1026
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/QUERY-MANAGER/$HOSTNAME:query-manager:1026/status?value=OUT_OF_SERVICE"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 1026
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            cpu: 500m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 600Mi
      restartPolicy: Always
      serviceAccountName: ""
status: {}
