apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: registry-subscription-manager
  name: registry-subscription-manager
  namespace: scorpio-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: registry-subscription-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: registry-subscription-manager
    spec:
      containers:
      - image: scorpiobroker/scorpio:RegistrySubscriptionManager_2.1.13
        imagePullPolicy: Always
        name: registry-subscription-manager
        ports:
        - containerPort: 2025
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/RegistrySubscriptionManager/$HOSTNAME:RegistrySubscriptionManager:2025/status?value=OUT_OF_SERVICE"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 2025
          initialDelaySeconds: 50
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            cpu: 500m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 600Mi
      restartPolicy: Always
      serviceAccountName: ""
status: {}

