{{- if .Values.atContextServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atContextServer.fullname" . }}
  labels:
    {{- include "atContextServer.labels" . | nindent 4 }}
spec:
  ports:
  - name: "27015"
    port: 27015
    targetPort: 27015
  selector:
    {{- include "atContextServer.matchLabels" . | nindent 4 }}
{{- end }}

