{{- if eq .Values.profile "dist" }}
{{- if .Values.configServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "configServer.fullname" . }}
  labels:
    {{- include "configServer.labels" . | nindent 4 }}
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    {{- include "configServer.matchLabels" . | nindent 4 }}
{{- end }}
{{- end }}
