{{- if .Values.entityManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "entityManager.fullname" . }}
  labels:
    {{- include "entityManager.labels" . | nindent 4 }}
spec:
  ports:
  - name: "1025"
    port: 1025
    targetPort: 1025
  selector:
    {{- include "entityManager.matchLabels" . | nindent 4 }}
{{- end }}
