{{- if eq .Values.profile "dist" }}
{{- if .Values.eureka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eureka.fullname" . }}
  labels:
    {{ include "eureka.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    {{ include "eureka.matchLabels" . | nindent 4 }}
{{- end }}
{{- end }}
