{{- if eq .Values.profile "dist" }}
{{- if and .Values.eureka.enabled .Values.eureka.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ include "eureka.fullname" . }}-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ include "eureka.fullname" . }}
 minReplicas: {{ .Values.eureka.hpa.minReplicas }}
 maxReplicas: {{ .Values.eureka.hpa.maxReplicas }}
 targetCPUUtilizationPercentage: {{ .Values.eureka.hpa.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
