{{ if eq .Values.profile "dist" }}
{{- if .Values.eureka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eureka.fullname" . }}
  labels:
    {{ include "eureka.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.eureka.replicas }}
  strategy:
  {{- with .Values.eureka.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eureka.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "eureka.labels" . | nindent 8 }}
        {{- with .Values.eureka.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.eureka.additionalAnnotations -}}
      annotations:
        {{- with .Values.eureka.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      containers:
      - image: {{ .Values.eureka.image.repository }}:{{ .Values.eureka.image.tag }}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end }}
        imagePullPolicy: {{ .Values.eureka.image.pullPolicy }}
        name: {{ include "eureka.fullname" . }}
        ports:
        - containerPort: 8761
          protocol: TCP
       

        resources:
{{ toYaml .Values.eureka.resources | indent 10 }}
      restartPolicy: {{ .Values.eureka.restartPolicy }}
      {{- if .Values.eureka.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.eureka.serviceAccount.name }}
      {{- end }}
      securityContext: {{ .Values.eureka.securityContext | toYaml }}
      terminationGracePeriodSeconds: {{ .Values.eureka.terminationGracePeriodSeconds }}
{{- end }}
{{- end }}
