{{- if eq .Values.profile "dist" }}
{{- if .Values.eureka.enabled }}
apiVersion: v1
kind: Service
metadata:  
  name: {{ include "eureka.fullname" . }}-node-port
  labels:
    {{- include "eureka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.eureka.service.type }}
  ports:
  - port: {{ .Values.eureka.service.port }}
    targetPort: {{ .Values.eureka.service.port }}
    {{- if and (eq .Values.eureka.service.type "NodePort") .Values.eureka.service.nodePort }}
    nodePort: {{ .Values.eureka.service.nodePort }}
    {{- else if eq .Values.eureka.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  selector:
    {{- include "eureka.matchLabels" . | nindent 4 }}
{{- end }}
{{- end }}
