{{- if eq .Values.profile "dist" }}
{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{ include "gateway.labels" . | nindent 4 }}
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    {{ include "gateway.matchLabels" . | nindent 4 }}
{{- end }}
{{- end }}
