{{- if and .Values.historyManager.enabled .Values.historyManager.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ include "historyManager.fullname" . }}-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ include "historyManager.fullname" . }}
 minReplicas: {{ .Values.historyManager.hpa.minReplicas }}
 maxReplicas: {{ .Values.historyManager.hpa.maxReplicas }}
 targetCPUUtilizationPercentage: {{ .Values.historyManager.hpa.targetCPUUtilizationPercentage }}
{{- end }}
