{{- if and .Values.registryManager.enabled .Values.registryManager.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ include "registryManager.fullname" . }}-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ include "registryManager.fullname" . }}
 minReplicas: {{ .Values.registryManager.hpa.minReplicas }}
 maxReplicas: {{ .Values.registryManager.hpa.maxReplicas }}
 targetCPUUtilizationPercentage: {{ .Values.registryManager.hpa.targetCPUUtilizationPercentage }}
{{- end }}
