{{- if .Values.registrySubscriptionManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "registrySubscriptionManager.fullname" . }}
  labels:
    {{ include "registrySubscriptionManager.labels" . | nindent 4 }}
spec:
  ports:
  - name: "2025"
    port: 2025
    targetPort: 2025
  selector:
    {{ include "registrySubscriptionManager.matchLabels" . | nindent 4 }}
{{- end }}
