{{- if .Values.registrySubscriptionManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "registrySubscriptionManager.fullname" . }}
  labels:
    {{ include "registrySubscriptionManager.labels" . | nindent 4 }}
spec:
  ports:
  - name: "1030"
    port: 1030
    targetPort: 1030
  selector:
    {{ include "registrySubscriptionManager.matchLabels" . | nindent 4 }}
{{- end }}
