{{- if and .Values.subscriptionManager.enabled .Values.subscriptionManager.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ include "subscriptionManager.fullname" . }}-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ include "subscriptionManager.fullname" . }}
 minReplicas: {{ .Values.subscriptionManager.hpa.minReplicas }}
 maxReplicas: {{ .Values.subscriptionManager.hpa.maxReplicas }}
 targetCPUUtilizationPercentage: {{ .Values.subscriptionManager.hpa.targetCPUUtilizationPercentage }}
{{- end }}
