mysettings:
  eureka:
    protocol: ${eureka.protocol:http}
    host: ${eureka.host:localhost}
    port: ${eureka.port:8761}
eurekaurl: ${mysettings.eureka.protocol}://${mysettings.eureka.host}:${mysettings.eureka.port}
spring:
  application:
    name: configserver
  main:
    lazy-initialization: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${eurekaurl}/eureka/
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 8888
logging:
  level:
    root: ERROR
#spring.cloud.config.server.git.uri=https://github.com/husseinterek/spring-cloud-repo.git
