spring:
  profiles:
    active: native
  application:
    name: configserver
  main:
    lazy-initialization: true
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
server:
  port: 8888
logging:
  level:
    root: ERROR
#spring.cloud.config.server.git.uri=https://github.com/husseinterek/spring-cloud-repo.git
