version: '3'

services:
  testserver:
    image: testserver
    ports:
     - "8080:8080"
  rabbitmq:
    image: rabbitmq
    ports:
     - "5672:5672"
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    depends_on:
      - rabbitmq