version: '3'

services:
  testserver:
    image: testserver
    ports:
      - "8080:8080"
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.26
    ports:
     - "5672:5672"
    environment:
      AMQ_USER: guest
      AMQ_PASSWORD: guest
    healthcheck:
      # This command uses Artemis's built-in tool to check if the node is running
      test: ["CMD", "/home/jboss/broker/bin/artemis", "check", "node", "--user", "guest", "--password", "guest"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s # Gives the broker 30 seconds to initialize before checks start
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ngb -d ngb"]
      interval: 10s
      timeout: 5s
      retries: 5
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-amqp-latest
    ports:
      - "9090:9090"
    environment:
      DBHOST: postgres
      CAMEL_COMPONENT_AMQP_HOST: artemis
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      artemis:
        condition: service_healthy