version: '3'

services:
  testserver:
    image: testserver
    ports:
     - "8080:8080"
  activemq:
    image: apache/activemq-classic
    ports:
     - "61616:61616"
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    depends_on:
      - activemq
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-activemq-latest
    ports:
      - "9090:9090"
    environment:
      DBHOST: postgres
      BUSHOST: activemq
    restart: on-failure
    depends_on:
      - postgres
      - activemq