scorpio.messageconnection.protocol=amqp:topic
scorpio.messageconnection.options=
#?addresses=localhost:5672
scorpio.messaging.maxSize=134217728
mp.messaging.incoming.registryretrieve.connector=smallrye-camel
mp.messaging.incoming.registryretrieve.endpoint-uri=${scorpio.messageconnection.protocol}:${scorpio.topics.registry}${scorpio.messageconnection.options}
mp.messaging.incoming.registryretrieve.auto.offset.reset=latest
mp.messaging.incoming.registryretrieve.broadcast=true
#readability block###########
mp.messaging.outgoing.entity.endpoint-uri=${scorpio.messageconnection.protocol}:${scorpio.topics.entity}${scorpio.messageconnection.options}
mp.messaging.outgoing.entity.connector=smallrye-camel
camel.component.amqp.host=localhost
camel.component.amqp.port=5672
quarkus.qpid-jms.wrap=true
quarkus.qpid-jms.url=amqp://${camel.component.amqp.host}:${camel.component.amqp.port}
quarkus.qpid-jms.username=guest
quarkus.qpid-jms.password=guest