scorpio.messageconnection.bootstrap.host=${bushost:localhost}
scorpio.messageconnection.bootstrap.port=${busport:5672}
bootstrap.servers=${scorpio.messageconnection.bootstrap.host}:${scorpio.messageconnection.bootstrap.port}
scorpio.messageconnection.protocol=rabbitmq
scorpio.messageconnection.options=
#?addresses=localhost:5672
scorpio.messaging.maxSize=134217728
mp.messaging.incoming.registryretrieve.connector=smallrye-camel
mp.messaging.incoming.registryretrieve.endpoint-uri=${scorpio.messageconnection.protocol}:${scorpio.topics.registry}${scorpio.messageconnection.options}
mp.messaging.incoming.registryretrieve.auto.offset.reset=latest
mp.messaging.incoming.registryretrieve.broadcast=true
#readability block###########
mp.messaging.outgoing.entity.endpoint-uri=${scorpio.messageconnection.protocol}:${scorpio.topics.entity}${scorpio.messageconnection.options}
mp.messaging.outgoing.entity.connector=smallrye-camel
camel.component.spring-rabbitmq.connection-factory.host=localhost
camel.component.spring-rabbitmq.connection-factory.port=5672
