mysettings:
  eureka:
    port: ${eureka.port:8761}
spring:
  application:
    name: eureka-server
server:
  port: ${mysettings.eureka.port}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    root: ERROR
