---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: acb7e4bc4d7b4e31bfa3872b87af3146ff9306ef
    app.quarkus.io/vcs-uri: https://github.com/scorpiobroker/scorpiobroker.git
    app.quarkus.io/build-timestamp: 2026-07-18 - 19:33:23 +0000
  labels:
    app.kubernetes.io/name: subscription-manager
    app.kubernetes.io/version: 6.0.2-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: subscription-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: subscription-manager
      app.kubernetes.io/version: 6.0.2-SNAPSHOT
  endpoints:
    - scheme: http
      targetPort: 10092
      path: /q/metrics
      interval: 10s
      honorLabels: true
