apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: entity-manager
  name: entity-manager
  namespace: scorpio-broker
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      service: entity-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: entity-manager
    spec:
      containers:
      - image: scorpiobroker/scorpio:EntityManager-no-eureka_latest
        imagePullPolicy: Always
        name: entity-manager
        ports:
        - containerPort: 1025
          protocol: TCP
      
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:1025/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:1025/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 5
          
  
        resources:
          limits:
            cpu: 875m
            memory: 2280Mi
          requests:
            cpu: 850m
            memory: 1850Mi
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
