apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: entity-manager
  name: entity-manager
  namespace: scorpio-broker
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      service: entity-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: entity-manager
    spec:
      containers:
      - image: scorpiobroker/entity-manager:spring-kafka-latest
        imagePullPolicy: Always
        name: entity-manager
        ports:
        - containerPort: 1025
          protocol: TCP
      
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 1025
          initialDelaySeconds: 50
          periodSeconds: 5
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 1025
          initialDelaySeconds: 50
          periodSeconds: 5
          successThreshold: 1    
  
        resources:
          limits:
            cpu: 875m
            memory: 2280Mi
          requests:
            cpu: 850m
            memory: 1850Mi
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
