apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: history-manager
  name: history-manager
  namespace: scorpio-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: history-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: history-manager
    spec:
      containers:
      - image: scorpiobroker/history-manager:java-kafka-latest
        imagePullPolicy: Always
        name: history-manager
        ports:
        - containerPort: 1040
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /q/health
            port: 1040
            scheme: HTTP
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /q/health
            port: 1040
            scheme: HTTP
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 5
  
        resources:
          limits:
            cpu: 500m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 600Mi
      restartPolicy: Always
      serviceAccountName: ""
status: {}
