apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: query-manager
  name: query-manager
  namespace: scorpio-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: query-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: query-manager
    spec:
      containers:
      - image: scorpiobroker/query-manager:spring-kafka-latest
        imagePullPolicy: Always
        name: query-manager
        ports:
        - containerPort: 1026
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 1026
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 1026
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
  
        resources:
          limits:
            cpu: 500m
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 600Mi
      restartPolicy: Always
      serviceAccountName: ""
status: {}
