server:
  port: 1025

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
bootstrap:
  servers: localhost:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/