apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
   type: pd-standard
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate