apiVersion: v1
kind: Service
metadata:
  labels:
    component: kafka
  name: kafka
  namespace: scorpio-broker
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    component: kafka
status:
  loadBalancer: {}
