apiVersion: v1
kind: Service
metadata:
  labels:
      component: postgres
  name: postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
      component: postgres
status:
  loadBalancer: {}
