apiVersion: v1
kind: Service
metadata:
  labels:
      component: zookeeper
  name: zookeeper
  namespace: scorpio-broker
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
  selector:
      component: zookeeper
status:
  loadBalancer: {}
