server:
  port: 27015

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092

bootstrap:
  servers: kafka:9092
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/