mysettings:
  kafka:
    bootstrap:
      host: ${kafka.host:localhost}
      port: ${kafka.port:9092}
bootstrap:
  servers: ${mysettings.kafka.bootstrap.host}:${mysettings.kafka.bootstrap.port}
spring:
#  mvc.pathpattern.matching-strategy: ant_path_matcher
  application:
    name: info-server
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
  kafka:
    admin:
      properties:
        cleanup:
          policy: compact
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${bootstrap.servers}
      bindings:
         ATCONTEXT_WRITE_CHANNEL:
          destination: ATCONTEXT
          contentType: application/json

server:
  port: 27015
  tomcat:
    max:
      threads: 20
#Entity-Manager properties
entity:
  topic: ENTITY
query:
  topic: QUERY
  result:
    topic: QUERY_RESULT
csource:
  query:
    topic: CONTEXT_REGISTRY_QUERY
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    restart:
      enabled: true
