mysettings:
  kafka:
    bootstrap:
      port: ${kafka.port:9092}
  eureka:
    protocol: ${eureka.protocol:http}
    host: ${eureka.host:eureka}
    port: ${eureka.port:8761}
eurekaurl: ${mysettings.eureka.protocol}://${mysettings.eureka.host}:${mysettings.eureka.port}
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaurl}/eureka/