apiVersion: v1
kind: Service
metadata:
  name: {{ include "scorpioBroker-aaio.fullname" . }}
  labels:
    {{- include "scorpioBroker-aaio.labels" . | nindent 4 }}
  namespace: scorpio-broker
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
      protocol: TCP
      name: "9090"
  selector:
    {{- include "scorpioBroker-aaio.selectorLabels" . | nindent 4 }}
