{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scorpioBroker-aaio.serviceAccountName" . }}
  namespace: scorpio-broker
  labels:
    {{- include "scorpioBroker-aaio.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
