apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: registry-subscription-hpa
 namespace: scorpio-broker
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: registry-subscription-manager
 minReplicas: 1
 maxReplicas: 5

