apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: sub-hpa
 namespace: scorpio-broker
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: subscription-manager
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 80