---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: 5b071181a29f961b54fc0809638df14e0a08191a
    app.quarkus.io/vcs-uri: https://github.com/scorpiobroker/scorpiobroker.git
    app.quarkus.io/build-timestamp: 2026-01-08 - 15:06:32 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "9090"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: aio-runner
    app.kubernetes.io/version: 6.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: aio-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 6.0.0-SNAPSHOT
      app.kubernetes.io/name: aio-runner
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.28.4
        app.quarkus.io/commit-id: 5b071181a29f961b54fc0809638df14e0a08191a
        app.quarkus.io/vcs-uri: https://github.com/scorpiobroker/scorpiobroker.git
        app.quarkus.io/build-timestamp: 2026-01-08 - 15:06:32 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "9090"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 6.0.0-SNAPSHOT
        app.kubernetes.io/name: aio-runner
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_FLYWAY_ACTIVE
              value: {{ .Values.app.envs.QUARKUS_FLYWAY_ACTIVE | quote }}
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.app.livenessProbe.httpGet.path }}
              port: {{ .Values.app.ports.http }}
              scheme: {{ .Values.app.livenessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.app.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
          name: aio-runner
          ports:
            - containerPort: {{ .Values.app.ports.http }}
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.app.readinessProbe.httpGet.path }}
              port: {{ .Values.app.ports.http }}
              scheme: {{ .Values.app.readinessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.app.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
          startupProbe:
            failureThreshold: {{ .Values.app.startupProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.app.startupProbe.httpGet.path }}
              port: {{ .Values.app.ports.http }}
              scheme: {{ .Values.app.startupProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.app.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.startupProbe.periodSeconds }}
            successThreshold: {{ .Values.app.startupProbe.successThreshold }}
            timeoutSeconds: {{ .Values.app.startupProbe.timeoutSeconds }}
      initContainers:
        - args:
            - job
            - aio-runner-flyway-init
          image: groundnuty/k8s-wait-for:no-root-v1.7
          imagePullPolicy: Always
          name: wait-for-flyway
      serviceAccountName: aio-runner
