---
apiVersion: batch/v1
kind: Job
metadata:
  name: registry-manager-flyway-init
spec:
  completionMode: NonIndexed
  template:
    metadata: {}
    spec:
      containers:
        - env:
            - name: QUARKUS_FLYWAY_ACTIVE
              value: "true"
            - name: QUARKUS_INIT_AND_EXIT
              value: "true"
          image: docker.io/demo/registry-manager:6.0.2-SNAPSHOT
          name: registry-manager-flyway-init
      restartPolicy: OnFailure
      serviceAccountName: registry-manager
