server:
  port: 2025

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

bootstrap:
  servers: kafka:9092
query:
  topic: QUERY
  result:
    topic: QUERY_RESULT

  
spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092

