server:
  port: 2025

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

bootstrap:
  servers: kafka:9092


  
spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: SpringBootHikariCP
    password: ngb
    url: jdbc:postgresql://postgres:5432/ngb?ApplicationName=ngb_registrymanager
    username: ngb
writer:
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: SpringBootHikariCP_Writer
    password: ngb
    url: jdbc:postgresql://postgres:5432/ngb?ApplicationName=ngb_storagemanager_writer
    username: ngb
  enabled: true
reader:
  enabled: true
  datasource:
    url: "jdbc:postgresql://postgres:5432/ngb?ApplicationName=ngb_storagemanager_reader"
    username: ngb
    password: ngb
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootHikariCP_Reader
      maxLifetime: 2000000
      connectionTimeout: 30000
  
