quarkus.application.name=aio-runner
quarkus.http.port=9090
quarkus.log.level=INFO
quarkus.ssl.native=true
quarkus.http.host=0.0.0.0
#quarkus.log.category."org.apache.kafka".level=ERROR
#quarkus.log.category."eu.neclab".level=DEBUG
quarkus.vertx.event-loops-pool-size=20
quarkus.native.additional-build-args=--initialize-at-run-time=org.apache.commons.lang3.RandomStringUtils
quarkus.vertx.prefer-native-transport=true
#quarkus.http.so-reuse-port=true
#quarkus.http.tcp-quick-ack=true
#quarkus.http.tcp-cork=true
#quarkus.http.tcp-fast-open=true
scorpio.postgres.host=${dbhost:localhost}
scorpio.postgres.port=${dbport:5432}
scorpio.postgres.username=${dbuser:ngb}
scorpio.postgres.password=${dbpass:ngb}
scorpio.postgres.database-name=${dbname:ngb}
scorpio.gateway.url=${gateway:http://localhost:9090}
scorpio.postgres.jdbcurl=jdbc:postgresql://${scorpio.postgres.host}:${scorpio.postgres.port}/${scorpio.postgres.database-name}?ApplicationName=${quarkus.application.name}
scorpio.messaging.duplicate=true
scorpio.querymanager.url=http://localhost:9090
scorpio.atcontexturl=http://localhost:9090
quarkus.rest-client.entity-service.url=${scorpio.querymanager.url}
quarkus.rest-client.atcontext-service.url=${scorpio.atcontexturl}
scorpio.atcontext.cache.duration=5m
quarkus.cache.caffeine.expire-after-access=20m
scorpio.history.autorecording=true
scorpio.history.max-limit=1000
scorpio.history.default-limit=50
scorpio.history.lastn=50
scorpio.history.max-lastn=1000
scorpio.history.batch-operations.create.max=1000
scorpio.history.batch-operations.upsert.max=1000
scorpio.history.batch-operations.update.max=1000
scorpio.history.batch-operations.delete.max=1000
scorpio.history.batch-operations.query.max=1000
scorpio.history.autorecordingthreadpoolsize=2
scorpio.history.autorecordingbuffersize=1000
scorpio.entity.max-limit=1000
scorpio.entity.default-limit=50
scorpio.entity.batch-operations.create.max=1000
scorpio.entity.batch-operations.upsert.max=1000
scorpio.entity.batch-operations.update.max=1000
scorpio.entity.batch-operations.delete.max=1000
scorpio.entity.batch-operations.query.max=1000
scorpio.registry.max-limit=1000
scorpio.registry.default-limit=50
scorpio.registry.autorecording=false
scorpio.registry.batch-operations.create.max=1000
scorpio.registry.batch-operations.upsert.max=1000
scorpio.registry.batch-operations.update.max=1000
scorpio.registry.batch-operations.delete.max=1000
scorpio.registry.batch-operations.query.max=1000
scorpio.subscription.max-limit=1000
scorpio.subscription.default-limit=50
scorpio.topics.entity=ENTITY
scorpio.topics.entity.zip=false
scorpio.topics.registry=REGISTRY
scorpio.topics.temporal=TEMPORAL
scorpio.topics.subalive=SUB_ALIVE
scorpio.topics.subsync=SUB_SYNC
scorpio.topics.histsync=HIST_SUB_SYNC
scorpio.entitymap.cleanup.ttl=90 sec
scorpio.entitymap.cleanup.schedule=30s
scorpio.startupdelay=5s
scorpio.sync.announcement-time=30s
scorpio.sync.check-time=90s
scorpio.ngsild.corecontext=https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.9.jsonld
#Database settings
quarkus.transaction-manager.default-transaction-timeout=300
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${scorpio.postgres.username}
quarkus.datasource.password=${scorpio.postgres.password}
quarkus.datasource.jdbc.url=${scorpio.postgres.jdbcurl}
quarkus.datasource.reactive.url=postgresql://${scorpio.postgres.host}:${scorpio.postgres.port}/${scorpio.postgres.database-name}
quarkus.datasource.reactive.shared=true
quarkus.datasource.reactive.cache-prepared-statements=true
quarkus.datasource.reactive.max-size=20
quarkus.datasource.reactive.idle-timeout=15s
#quarkus.datasource.reactive.event-loop-size=100
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.connect-retries=10
quarkus.flyway.repair-at-start=true
scorpio.alltypesub.type=*
scorpio.registry.subscription.checkinterval=30s
scorpio.subscription.checkinterval=2s
scorpio.federation.updaterate=600s
scorpio.federation.registrationtype=types
scorpio.federation.hosts=none
scorpio.federation.timeout=2000
scorpio.federation.limit=1000
quarkus.http.limits.max-initial-line-length=50000
scorpio.history.syncchecktime=5000
scorpio.messaging.maxSize=2147483646
quarkus.helm.icon=../img/ScorpioLogo.svg
quarkus.helm.output-directory=../helm/${quarkus.application.name}
quarkus.kubernetes.output-directory=../kubernetes/${quarkus.application.name}
