mysettings:
  kafka:
    bootstrap:
      host: ${kafka.host:kafka}
  eureka:
    host: ${eureka.host:eureka}
  postgres:
    host: ${postgres.host:postgres}
  gateway:
    host: ${gateway.host:}
eurekaurl: ${mysettings.eureka.protocol}://${mysettings.eureka.host}:${mysettings.eureka.port}
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaurl}/eureka/
