server:
  port: 27015
mysettings:
  eureka:
    protocol: ${eureka.protocol:http}
    host: ${eureka.host:localhost}
    port: ${eureka.port:8761}
eurekaurl: ${mysettings.eureka.protocol}://${mysettings.eureka.host}:${mysettings.eureka.port}
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaurl}/eureka/
