---
apiVersion: batch/v1
kind: Job
metadata:
  name: registry-subscription-manager-flyway-init
spec:
  completionMode: NonIndexed
  template:
    metadata: {}
    spec:
      containers:
        - env:
            - name: QUARKUS_INIT_AND_EXIT
              value: "true"
            - name: QUARKUS_FLYWAY_ACTIVE
              value: "true"
          image: scorpiobroker/registry-subscription-manager:java-kafka-latest
          name: registry-subscription-manager-flyway-init
      restartPolicy: OnFailure
      serviceAccountName: registry-subscription-manager
