---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: registry-subscription-manager
    app.kubernetes.io/version: 6.0.1-SNAPSHOT
  name: registry-subscription-manager-view-jobs
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-jobs
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: registry-subscription-manager
