---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: 555496e2de3765466a67664fc5046ce0499b0505
    app.quarkus.io/vcs-uri: https://github.com/scorpiobroker/scorpiobroker.git
    app.quarkus.io/build-timestamp: 2026-01-12 - 13:29:46 +0000
  labels:
    app.kubernetes.io/name: registry-subscription-manager
    app.kubernetes.io/version: 6.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: registry-subscription-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: registry-subscription-manager
      app.kubernetes.io/version: 6.0.1-SNAPSHOT
  endpoints:
    - scheme: http
      targetPort: 10094
      path: /q/metrics
      interval: 10s
      honorLabels: true
