---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: c4191904d8ab780c45d443d7401f101fa679f07d
    app.quarkus.io/vcs-uri: https://github.com/ScorpioBroker/ScorpioBroker.git
    app.quarkus.io/build-timestamp: 2026-07-22 - 15:57:29 +0000
  labels:
    app.kubernetes.io/name: registry-subscription-manager
    app.kubernetes.io/version: 6.0.2-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: registry-subscription-manager
