{{- if .Values.entityManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "entityManager.fullname" . }}
  labels:
    {{- include "entityManager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.entityManager.replicas }}
  strategy:
  {{- with .Values.entityManager.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "entityManager.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "entityManager.labels" . | nindent 8 }}
        {{- with .Values.entityManager.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.entityManager.additionalAnnotations -}}
      annotations:
        {{- with .Values.entityManager.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      containers:
        {{- if eq .Values.profile "dist"  }}
      - image: {{ .Values.entityManager.image.repository }}:{{ .Values.entityManager.image.tag }}
        {{ else }}
      - image: {{ .Values.entityManager.image.repository }}:{{ .Values.entityManager.image.no_eureka_tag }}
        {{ end }}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end }}
        imagePullPolicy: {{ .Values.entityManager.image.pullPolicy }}
        name: {{ include "entityManager.fullname" . }}
        ports:
        - containerPort: 1025
          protocol: TCP
        {{- if eq .Values.profile "dist"  }}
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://{{ .Values.eureka.hostname }}:{{ .Values.eureka.port }}/eureka/apps/ENTITY-MANAGER/$HOSTNAME:entity-manager:1025/status?value=OUT_OF_SERVICE"
        {{ end }}
     
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 1025
          initialDelaySeconds: {{ .Values.entityManager.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.entityManager.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.entityManager.readinessProbe.successThreshold }}
         
      
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 1025
          initialDelaySeconds: {{ .Values.entityManager.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.entityManager.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.entityManager.livenessProbe.successThreshold }}
             
        resources:
{{ toYaml .Values.entityManager.resources | indent 10 }}
      restartPolicy: {{ .Values.entityManager.restartPolicy }}
      {{- if .Values.entityManager.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.entityManager.serviceAccount.name }}
      {{- end }}
      securityContext: {{ .Values.entityManager.securityContext | toYaml }}
      terminationGracePeriodSeconds: {{ .Values.entityManager.terminationGracePeriodSeconds }}
{{- end }}

