---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: 59675831de0ce7a6ee91ff20efd25a8e6581e7a9
    app.quarkus.io/vcs-uri: https://github.com/scorpiobroker/scorpiobroker.git
    app.quarkus.io/build-timestamp: 2026-06-24 - 13:53:19 +0000
  labels:
    app.kubernetes.io/name: history-entity-manager
    app.kubernetes.io/version: 6.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: history-entity-manager
