---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: acb7e4bc4d7b4e31bfa3872b87af3146ff9306ef
    app.quarkus.io/vcs-uri: https://github.com/scorpiobroker/scorpiobroker.git
    app.quarkus.io/build-timestamp: 2026-07-18 - 19:34:23 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "10095"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: history-entity-manager
    app.kubernetes.io/version: 6.0.2-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: history-entity-manager
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: history-entity-manager
    app.kubernetes.io/version: 6.0.2-SNAPSHOT
  type: ClusterIP
