scorpio.messageconnection.bootstrap.host=${bushost:localhost}
scorpio.messageconnection.bootstrap.port=${busport:5672}
bootstrap.servers=${scorpio.messageconnection.bootstrap.host}:${scorpio.messageconnection.bootstrap.port}
scorpio.messageconnection.protocol=amqp
scorpio.messageconnection.options=
#?addresses=localhost:5672
scorpio.messaging.maxSize=134217728
mp.messaging.incoming.registryretrieve.connector=smallrye-camel
mp.messaging.incoming.registryretrieve.endpoint-uri=${scorpio.messageconnection.protocol}:${scorpio.topics.registry}${scorpio.messageconnection.options}
mp.messaging.incoming.registryretrieve.auto.offset.reset=latest
mp.messaging.incoming.registryretrieve.broadcast=true
#readability block###########
mp.messaging.incoming.entityretrieve.connector=smallrye-camel
mp.messaging.incoming.entityretrieve.endpoint-uri=${scorpio.messageconnection.protocol}:${scorpio.topics.entity}${scorpio.messageconnection.options}
mp.messaging.incoming.entityretrieve.auto.offset.reset=latest
mp.messaging.incoming.entityretrieve.broadcast=true
#readability block###########
mp.messaging.outgoing.histsync.connector=smallrye-camel
mp.messaging.outgoing.histsync.endpoint-uri=${scorpio.messageconnection.protocol}:${scorpio.topics.histsync}${scorpio.messageconnection.options}
mp.messaging.incoming.histsyncretrieve.connector=smallrye-camel
mp.messaging.incoming.histsyncretrieve.endpoint-uri=${scorpio.messageconnection.protocol}:${scorpio.topics.histsync}${scorpio.messageconnection.options}
mp.messaging.incoming.histsyncretrieve.auto.offset.reset=latest
camel.component.amqp.host=localhost
camel.component.amqp.port=5672
quarkus.qpid-jms.wrap=true
quarkus.qpid-jms.url=amqp://${camel.component.amqp.host}:${camel.component.amqp.port}