name: API_TEST
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2     
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Build testserver
        run: |
          cd testserver
          docker build -t testserver .
      - name: Building Scorpio Components
        run: |
          mvn clean package -DskipTests -Pdocker-aaio-no-eureka -B
      - name: Running Scorpio 
        run: |
           docker-compose -f docker-compose-test.yml up > dockerlog.out &
           sleep 40
      - name: newman action
        continue-on-error: true
        uses: matt-ball/newman-action@master
        with:
          collection: api-test.json
          environment: api-test-environment.json
      - name: Stopping Scorpio 
        run: docker-compose -f docker-compose-aaio-dev.yml down -d
      - name: Print log
        run: cat dockerlog.out
      
      
         
         
         
