# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API_TEST
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2     
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup PostgreSQL with Postgis 
        uses: huaxk/postgis-action@v1.0.0
        with:
         postgresql version: 9.6
         postgresql db: ngb
         postgresql user: ngb
         postgresql password: ngb
      - name: Start Bitname Kafka
        uses: bbcCorp/kafka-actions@v1
        env:
          KAFKA_ADVERTISED_HOST_NAME: kafka
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_LOG_RETENTION_MS: 10000
          KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
      - name: Building Scorpio Components
        run: |
         mvn clean package -DskipTests -Dcitest -Paaio-no-eureka -B
         java -Dspring.profiles.active=test -jar ./AllInOneRunner/target/AllInOneRunner.jar &
         while [ `curl -s -o /dev/null -w "%{http_code}" http://localhost:9090/actuator/health` -ne 200 ]; do sleep 2; done
      - name: newman action
        uses: matt-ball/newman-action@master
        with:
         collection: api-test.json
         environment: api-test-environment.json
      
      
         
         
         
