name: Release Java version
on: 
  push:
    branches: "preview-release/**"
jobs:
  build-java-sqs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ECR_ID }}
          aws-secret-access-key: ${{ secrets.ECR_TOKEN }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Build testserver
        run: |
          cd testserver
          docker build -t testserver .
      - name: Get release number
        id: get-id
        run: |
          id=$(echo ${{github.ref_name}} | cut -d/ -f2)
          echo "::set-output name=id::$id"
      - name: build-java-with-sqs
        run: |
          mvn clean package -DskipTests -Dsqs -Psqs -Ddocker -Ddocker-tag=java-sqs-${{steps.get-id.outputs.id}} -Dos=java -Dquarkus.profile=sqs
      - name: docker tag 
        run: |
          docker tag scorpiobroker/at-context-server:java-sqs-${{steps.get-id.outputs.id}} scorpiobroker/at-context-server:java-sqs-latest
          docker tag scorpiobroker/history-entity-manager:java-sqs-${{steps.get-id.outputs.id}} scorpiobroker/history-entity-manager:java-sqs-latest
          docker tag scorpiobroker/history-query-manager:java-sqs-${{steps.get-id.outputs.id}} scorpiobroker/history-query-manager:java-sqs-latest
          docker tag scorpiobroker/registry-subscription-manager:java-sqs-${{steps.get-id.outputs.id}} scorpiobroker/registry-subscription-manager:java-sqs-latest
          docker tag scorpiobroker/registry-manager:java-sqs-${{steps.get-id.outputs.id}} scorpiobroker/registry-manager:java-sqs-latest
          docker tag scorpiobroker/subscription-manager:java-sqs-${{steps.get-id.outputs.id}} scorpiobroker/subscription-manager:java-sqs-latest
          docker tag scorpiobroker/query-manager:java-sqs-${{steps.get-id.outputs.id}} scorpiobroker/query-manager:java-sqs-latest
          docker tag scorpiobroker/entity-manager:java-sqs-${{steps.get-id.outputs.id}} scorpiobroker/entity-manager:java-sqs-latest
          docker tag scorpiobroker/all-in-one-runner:java-sqs-${{steps.get-id.outputs.id}} scorpiobroker/all-in-one-runner:java-sqs-latest
          docker tag scorpiobroker/at-context-server:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/at-context-server:java-sqs-latest
          docker tag scorpiobroker/history-entity-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/history-entity-manager:java-sqs-latest
          docker tag scorpiobroker/history-query-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/history-query-manager:java-sqs-latest
          docker tag scorpiobroker/registry-subscription-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/registry-subscription-manager:java-sqs-latest
          docker tag scorpiobroker/registry-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/registry-manager:java-sqs-latest
          docker tag scorpiobroker/subscription-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/subscription-manager:java-sqs-latest
          docker tag scorpiobroker/query-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/query-manager:java-sqs-latest
          docker tag scorpiobroker/entity-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/entity-manager:java-sqs-latest
          docker tag scorpiobroker/all-in-one-runner:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/all-in-one-runner:java-sqs-latest
          docker tag scorpiobroker/at-context-server:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/at-context-server:java-sqs-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/history-entity-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/history-entity-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/history-query-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/history-query-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/registry-subscription-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/registry-subscription-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/registry-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/registry-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/subscription-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/subscription-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/query-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/query-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/entity-manager:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/entity-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker tag scorpiobroker/all-in-one-runner:java-sqs-${{steps.get-id.outputs.id}} ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/all-in-one-runner:java-sqs-${{steps.get-id.outputs.id}}
      - name: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: docker tag and push
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/at-context-server:java-sqs-${{steps.get-id.outputs.id}}
          docker push ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/history-entity-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker push ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/history-query-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker push ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/registry-subscription-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker push ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/registry-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker push ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/subscription-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker push ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/query-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker push ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/entity-manager:java-sqs-${{steps.get-id.outputs.id}}
          docker push ${{ steps.login-ecr.outputs.registry }}/scorpiobroker/all-in-one-runner:java-sqs-${{steps.get-id.outputs.id}}
