---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: at-context-server
    app.kubernetes.io/version: 6.0.2-SNAPSHOT
  name: at-context-server-view-jobs
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-jobs
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: at-context-server
