---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.28.4
    app.quarkus.io/commit-id: c4191904d8ab780c45d443d7401f101fa679f07d
    app.quarkus.io/vcs-uri: https://github.com/ScorpioBroker/ScorpioBroker.git
    app.quarkus.io/build-timestamp: 2026-07-22 - 15:56:54 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "10097"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: at-context-server
    app.kubernetes.io/version: 6.0.2-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: at-context-server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: at-context-server
    app.kubernetes.io/version: 6.0.2-SNAPSHOT
  type: ClusterIP
