trigger:
- quarkus-release/4.1.15

variables:
  tag: java-4.1.15-custom-$(Build.BuildId)
  SelfHostedPoolName: iot-shared-ubuntu-20.04

pool:
  name: $(SelfHostedPoolName)

steps:
- task: Docker@2
  displayName: Login to ACR docker registry
  inputs:    
    command: login
    containerRegistry: iotsharedacr-registry-ServiceConnection

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'
    options: '-Dos=java -B -Dmaven.test.skip=true'    

- task: Docker@2
  displayName: Build docker image for AllInOneRunner only
  inputs:    
    command: build
    buildContext: AllInOneRunner
    dockerfile: AllInOneRunner/src/main/resources/dockerfiles/dockerfile-java
    tags: |
      $(tag)

- task: Docker@2
  displayName: Push docker image
  inputs:
    command: push
    containerRegistry: iotsharedacr-registry-ServiceConnection
    repository: scorpiobroker/all-in-one-runner
    tags: |
      $(tag)
