trigger:
- quarkus-release/4.1.15

variables:
  javaKafkaTag: java-kafka-4.1.15-$(Build.BuildId)
  SelfHostedPoolName: iot-shared-ubuntu-20.04

pool:
  name: $(SelfHostedPoolName)

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
    options: '-DskipTests -Dmaven.test.skip=true -Dkafka -Pkafka -Dos=java -Dquarkus.profile=kafka -B'
    # Not using maven maven docker plugin as it is not maintained anymore - building docker image in separate task
    # options: '-DskipTests -Dmaven.test.skip=true -Dkafka -Pkafka -Ddocker -Ddocker-tag=$(tag) -Dos=java -Dquarkus.profile=kafka -B'

- task: Docker@2
  displayName: Login to ACR docker registry
  inputs:    
    command: login
    containerRegistry: iotsharedacr-registry-ServiceConnection

- task: Docker@2
  displayName: Build and push docker image for AllInOneRunner
  inputs:    
    command: buildAndPush
    buildContext: AllInOneRunner
    dockerfile: AllInOneRunner/src/main/resources/dockerfiles/dockerfile-java
    repository: iotsharedacr.azurecr.io/scorpiobroker/all-in-one-runner
    tags: |
      java-kafka-4.1.15-$(Build.BuildId)
      java-kafka-4.1.15
      java-kafka-latest

- script: docker images

# - script: |
#     docker tag scorpiobroker/all-in-one-runner:$(javaKafkaTag) iotsharedacr.azurecr.io/scorpiobroker/all-in-one-runner:java-kafka-4.1.15-$(Build.BuildId)
#     docker tag scorpiobroker/all-in-one-runner:$(javaKafkaTag) iotsharedacr.azurecr.io/scorpiobroker/all-in-one-runner:java-kafka-4.1.15
#     docker tag scorpiobroker/all-in-one-runner:$(javaKafkaTag) iotsharedacr.azurecr.io/scorpiobroker/all-in-one-runner:java-kafka-latest
#     docker images

# - script: |
#     docker push iotsharedacr.azurecr.io/scorpiobroker/all-in-one-runner:java-kafka-4.1.15-$(Build.BuildId)
#     docker push iotsharedacr.azurecr.io/scorpiobroker/all-in-one-runner:java-kafka-4.1.15
#     docker push iotsharedacr.azurecr.io/scorpiobroker/all-in-one-runner:java-kafka-latest

