trigger:
- quarkus-release/4.1.15

variables:
  tag: java-4.1.15-custom-$(Build.BuildId)
  SelfHostedPoolName: ctoofficelab-dev-ubuntu-20.04

pool:
  name: $(SelfHostedPoolName)

# resources:
#   pipelines:
#     - pipeline: ci-pipeline
#       project: Fiware
#       source: scorpiobroker-ci-pipeline
#       branch: main
#   repositories:
#   - repository: kubernetes-platform
#     type: git
#     name: FT Operations/kubernetes-platform
#     ref: refs/tags/v3.2.1
#     endpoint: KMDDK-organization-GIT

steps:
# - task: Docker@2
#   displayName: Login to ACR docker registry
#   inputs:    
#     command: login
#     containerRegistry: ctoofficelabacr

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'
    options: '-Dos=java -B -Dmaven.test.skip=true'    

- task: Docker@2
  displayName: Build docker image for AllInOneRunner only
  inputs:    
    command: build
    buildContext: AllInOneRunner
    dockerfile: AllInOneRunner/src/main/resources/dockerfiles/dockerfile-java
    tags: |
      $(tag)

- script: docker images

- task: Docker@2
  displayName: Push docker image
  inputs:
    command: push
    containerRegistry: ctoofficelabacr
    repository: ctoofficelabacr.azurecr.io/scorpiobroker/all-in-one-runner
    tags: |
      $(tag)




# publish to deocker registry
  # container_registry_resource_group_name_shared_acr = "iot-shared-ACR-rg"
  # container_registry_name_shared_acr                = "iotsharedacr"


